name: check-style
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: install requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: run style check
      run: |
        flake8 .
